version: '3'
services:
  collector:
    build:
      context: .
      dockerfile: ./docker/twtlvidplayer-collector/Dockerfile
    volumes:
      - ./docker/data:/app/backend/data

  web:
    build:
      context: .
      dockerfile: ./docker/twtlvidplayer-web/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./docker/data:/app/backend/data

